project:
  type: book
  output-dir: docs

lang: es

book:
  title: "Aprendizaje y Clasificación Automática con R"
  subtitle: "Un enfoque práctico con datos abiertos reales"
  author: "MI Jesús Gilberto Rodríguez Escobedo"
  date: today
  version: "0.4"
  downloads: [pdf]
  site-url: "https://gilbertorodriguez59.github.io/libro-machine-learning-r/"
  chapters:
    - index.qmd
    - 00-licencia-y-citacion.qmd
    - 01-introduccion.qmd
    - 02-preparacion-datos.qmd
    - 03-analisis-exploratorio.qmd
    - 04-regresion-logistica.qmd
    - 05-knn.qmd
    - 06-arboles-decision.qmd
    - 07-random-forest.qmd

execute:
  echo: true
  warning: false
  message: false
  freeze: auto
  fig_crop: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    html-math-method: mathjax
    fig-width: 8
    fig-height: 5
    fig-align: center

  pdf:
    documentclass: book
    toc: true
    toc-title: "Índice general"
    number-sections: true
    colorlinks: true
    geometry:
      - margin=2.5cm
    fontsize: 11pt
    keep-tex: true
    pdf-engine: lualatex
    fig-width: 7
    fig-height: 4.5
    include-in-header:
      text: |
        \renewcommand{\contentsname}{Índice general}
        \renewcommand{\chaptername}{Capítulo}
        \usepackage{xcolor}
        \definecolor{azulLibro}{HTML}{1F4E79}
        \definecolor{turquesaLibro}{HTML}{19A7AE}
        \usepackage{sectsty}
        \chapterfont{\color{azulLibro}}
        \sectionfont{\color{azulLibro}}
        \subsectionfont{\color{turquesaLibro}}
