{
  "hash": "8bb315efc570256deb40bce9a9ee2c78",
  "result": {
    "engine": "knitr",
    "markdown": "# Análisis exploratorio de datos\n\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n\n## Objetivos del capítulo\n\nAl finalizar este capítulo, el lector será capaz de:\n\n- Explicar qué es el análisis exploratorio de datos.\n- Cargar una base preparada previamente.\n- Revisar la estructura de un conjunto de datos.\n- Analizar la distribución de una variable respuesta.\n- Construir tablas de frecuencia.\n- Elaborar gráficas de barras con `ggplot2`.\n- Interpretar patrones iniciales antes de construir modelos.\n\n## Introducción\n\nDespués de preparar los datos, el siguiente paso en un proyecto de aprendizaje automático es explorarlos.\n\nEl **análisis exploratorio de datos**, también conocido como *Exploratory Data Analysis* o **EDA**, consiste en revisar, resumir, visualizar e interpretar los datos antes de construir modelos.\n\n## Fundamento matemático del análisis exploratorio\n\nSi una variable categórica tiene categorías $c_1, c_2, \\ldots, c_k$, la frecuencia absoluta de una categoría $c_j$ se puede representar como:\n\n$$\nn_j = \\sum_{i=1}^{n} I(y_i = c_j)\n$$\n\ndonde $I(y_i = c_j)$ es una función indicadora:\n\n$$\nI(y_i = c_j) =\n\\left\\{\n\\begin{array}{ll}\n1, & \\text{si } y_i = c_j \\\\\n0, & \\text{si } y_i \\neq c_j\n\\end{array}\n\\right.\n$$\n\nLa proporción de la categoría $c_j$ es:\n\n$$\np_j = \\frac{n_j}{n}\n$$\n\nEn nuestro caso, una proporción importante es:\n\n$$\np_{\\text{víctimas}} =\n\\frac{\\text{número de accidentes con víctimas}}\n{\\text{número total de accidentes}}\n$$\n\n## Proporciones condicionales\n\nPodemos estudiar la proporción de accidentes con víctimas dado un tipo de accidente:\n\n$$\nP(\\text{Con víctimas} \\mid \\text{Tipo de accidente})\n$$\n\nDe forma empírica, esta proporción se calcula como:\n\n$$\n\\hat{P}(\\text{Con víctimas} \\mid T = t)\n=\n\\frac{\n\\text{número de accidentes con víctimas del tipo } t\n}{\n\\text{número total de accidentes del tipo } t\n}\n$$\n\n## Algoritmo general del análisis exploratorio\n\n```text\nAlgoritmo: Análisis exploratorio de datos\n\nEntrada:\n  - Base de datos preparada\n  - Variable respuesta\n  - Variables predictoras\n\nProceso:\n  1. Revisar dimensiones de la base.\n  2. Revisar nombres y tipos de variables.\n  3. Calcular frecuencias de la variable respuesta.\n  4. Calcular proporciones de la variable respuesta.\n  5. Analizar variables temporales, categóricas y numéricas.\n  6. Construir gráficas exploratorias.\n  7. Cruzar variables predictoras con la variable respuesta.\n  8. Identificar patrones, desbalances y posibles problemas.\n\nSalida:\n  - Tablas descriptivas\n  - Gráficas exploratorias\n  - Primeras hipótesis sobre los datos\n```\n\n## Cargar paquetes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(dplyr)\nlibrary(ggplot2)\n```\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Cargar la base preparada\n\n\n::: {.cell}\n\n```{.r .cell-code}\nruta_atus_ml <- \"datos/atus_ml_preparado.csv\"\nfile.exists(ruta_atus_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (file.exists(ruta_atus_ml)) {\n  atus_ml <- read_csv(ruta_atus_ml, show_col_types = FALSE)\n  print(\"Base preparada cargada correctamente.\")\n} else {\n  atus_ml <- NULL\n  print(\"No se encontró el archivo datos/atus_ml_preparado.csv. Ejecuta primero el capítulo 2.\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Base preparada cargada correctamente.\"\n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Preparar variables para el análisis exploratorio\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  atus_ml <- atus_ml |>\n    mutate(\n      ID_HORA_NUM = as.numeric(ID_HORA),\n      DIASEMANA = factor(\n        DIASEMANA,\n        levels = c(\"lunes\", \"Martes\", \"Miercoles\", \"Jueves\", \"Viernes\", \"Sabado\", \"Domingo\")\n      ),\n      accidente_con_victimas = factor(\n        accidente_con_victimas,\n        levels = c(\"Con víctimas\", \"Solo daños\")\n      )\n    )\n}\n```\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Primer vistazo a la base\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  dim(atus_ml)\n  head(atus_ml)\n  names(atus_ml)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"accidente_con_victimas\" \"MES\"                    \"ID_HORA\"               \n[4] \"DIASEMANA\"              \"TIPACCID\"               \"CAUSAACCI\"             \n[7] \"ID_HORA_NUM\"           \n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Estructura de los datos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  str(atus_ml)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [390,627 × 7] (S3: tbl_df/tbl/data.frame)\n $ accidente_con_victimas: Factor w/ 2 levels \"Con víctimas\",..: 2 2 1 2 2 1 1 2 2 2 ...\n $ MES                   : chr [1:390627] \"01\" \"01\" \"01\" \"01\" ...\n $ ID_HORA               : chr [1:390627] \"02\" \"03\" \"04\" \"05\" ...\n $ DIASEMANA             : Factor w/ 7 levels \"lunes\",\"Martes\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ TIPACCID              : chr [1:390627] \"Colisión con vehículo automotor\" \"Colisión con objeto fijo\" \"Colisión con peatón (atropellamiento)\" \"Colisión con objeto fijo\" ...\n $ CAUSAACCI             : chr [1:390627] \"Conductor\" \"Conductor\" \"Conductor\" \"Conductor\" ...\n $ ID_HORA_NUM           : num [1:390627] 2 3 4 5 6 7 12 13 18 20 ...\n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Distribución de la variable respuesta\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  table(atus_ml$accidente_con_victimas)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCon víctimas   Solo daños \n       68108       322519 \n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  round(100 * prop.table(table(atus_ml$accidente_con_victimas)), 2)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCon víctimas   Solo daños \n       17.44        82.56 \n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Interpretación de la variable respuesta\n\nEn esta base se observa un desbalance importante: aproximadamente 82.56% de los accidentes corresponden a solo daños, mientras que 17.44% corresponden a accidentes con víctimas.\n\n## Gráfica de la variable respuesta\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  ggplot(atus_ml, aes(x = accidente_con_victimas)) +\n    geom_bar() +\n    labs(\n      title = \"Distribución de accidentes según presencia de víctimas\",\n      x = \"Clase del accidente\",\n      y = \"Número de accidentes\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](03-analisis-exploratorio_files/figure-html/unnamed-chunk-10-1.png){width=840}\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Accidentes por mes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  accidentes_mes <- atus_ml |>\n    count(MES) |>\n    arrange(as.numeric(MES))\n\n  accidentes_mes\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   MES       n\n   <chr> <int>\n 1 01    31600\n 2 02    32208\n 3 03    33237\n 4 04    32666\n 5 05    34665\n 6 06    31737\n 7 07    30062\n 8 08    31800\n 9 09    31351\n10 10    33771\n11 11    34047\n12 12    33483\n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  ggplot(accidentes_mes, aes(x = factor(MES, levels = sort(unique(as.numeric(MES)))), y = n)) +\n    geom_col() +\n    labs(\n      title = \"Número de accidentes por mes\",\n      x = \"Mes\",\n      y = \"Número de accidentes\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](03-analisis-exploratorio_files/figure-html/unnamed-chunk-12-1.png){width=840}\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Accidentes por hora del día\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  accidentes_hora <- atus_ml |>\n    count(ID_HORA_NUM) |>\n    arrange(ID_HORA_NUM)\n\n  accidentes_hora\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 24 × 2\n   ID_HORA_NUM     n\n         <dbl> <int>\n 1           0  9143\n 2           1  7400\n 3           2  6594\n 4           3  5694\n 5           4  4880\n 6           5  4986\n 7           6  8034\n 8           7 15159\n 9           8 20666\n10           9 19486\n# ℹ 14 more rows\n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  ggplot(accidentes_hora, aes(x = ID_HORA_NUM, y = n)) +\n    geom_col() +\n    scale_x_continuous(breaks = 0:23) +\n    labs(\n      title = \"Número de accidentes por hora del día\",\n      x = \"Hora del día\",\n      y = \"Número de accidentes\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](03-analisis-exploratorio_files/figure-html/unnamed-chunk-14-1.png){width=840}\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Accidentes por día de la semana\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  accidentes_dia <- atus_ml |>\n    count(DIASEMANA) |>\n    arrange(DIASEMANA)\n\n  accidentes_dia\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  DIASEMANA     n\n  <fct>     <int>\n1 lunes     69412\n2 Martes    51215\n3 Miercoles 51580\n4 Jueves    50954\n5 Viernes   56708\n6 Sabado    58321\n7 Domingo   52437\n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  ggplot(accidentes_dia, aes(x = DIASEMANA, y = n)) +\n    geom_col() +\n    coord_flip() +\n    labs(\n      title = \"Número de accidentes por día de la semana\",\n      x = \"Día de la semana\",\n      y = \"Número de accidentes\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](03-analisis-exploratorio_files/figure-html/unnamed-chunk-16-1.png){width=840}\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Accidentes por tipo de accidente\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  accidentes_tipo <- atus_ml |>\n    count(TIPACCID) |>\n    arrange(desc(n))\n\n  accidentes_tipo\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 2\n   TIPACCID                                   n\n   <chr>                                  <int>\n 1 Colisión con vehículo automotor       224720\n 2 Colisión con motocicleta               61869\n 3 Colisión con objeto fijo               43119\n 4 Certificado cero                       15678\n 5 Volcadura                              13371\n 6 Colisión con peatón (atropellamiento)  11052\n 7 Salida del camino                      10067\n 8 Colisión con ciclista                   4033\n 9 Otro                                    2934\n10 Caída de pasajero                       2153\n11 Colisión con animal                      884\n12 Incendio                                 455\n13 Colisión con ferrocarril                 292\n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  accidentes_tipo_top <- accidentes_tipo |>\n    slice_max(n, n = 10)\n\n  ggplot(accidentes_tipo_top, aes(x = reorder(TIPACCID, n), y = n)) +\n    geom_col() +\n    coord_flip() +\n    labs(\n      title = \"Tipos de accidente más frecuentes\",\n      x = \"Tipo de accidente\",\n      y = \"Número de accidentes\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](03-analisis-exploratorio_files/figure-html/unnamed-chunk-18-1.png){width=840}\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Accidentes por causa presunta\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  accidentes_causa <- atus_ml |>\n    count(CAUSAACCI) |>\n    arrange(desc(n))\n\n  accidentes_causa\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  CAUSAACCI                      n\n  <chr>                      <int>\n1 Conductor                 360051\n2 Certificado cero           15678\n3 Mala condición del camino   5991\n4 Falla del vehículo          3978\n5 Otra                        2639\n6 Peatón o pasajero           2290\n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  accidentes_causa_top <- accidentes_causa |>\n    slice_max(n, n = 10)\n\n  ggplot(accidentes_causa_top, aes(x = reorder(CAUSAACCI, n), y = n)) +\n    geom_col() +\n    coord_flip() +\n    labs(\n      title = \"Causas presuntas más frecuentes\",\n      x = \"Causa presunta\",\n      y = \"Número de accidentes\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](03-analisis-exploratorio_files/figure-html/unnamed-chunk-20-1.png){width=840}\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Relación entre tipo de accidente y presencia de víctimas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  tipos_top <- atus_ml |>\n    count(TIPACCID) |>\n    slice_max(n, n = 10) |>\n    pull(TIPACCID)\n\n  atus_tipo_top <- atus_ml |>\n    filter(TIPACCID %in% tipos_top)\n\n  ggplot(atus_tipo_top, aes(x = TIPACCID, fill = accidente_con_victimas)) +\n    geom_bar(position = \"fill\") +\n    coord_flip() +\n    labs(\n      title = \"Proporción de accidentes con víctimas según tipo de accidente\",\n      x = \"Tipo de accidente\",\n      y = \"Proporción\",\n      fill = \"Clase\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](03-analisis-exploratorio_files/figure-html/unnamed-chunk-21-1.png){width=840}\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Relación entre hora y presencia de víctimas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  ggplot(atus_ml, aes(x = ID_HORA_NUM, fill = accidente_con_victimas)) +\n    geom_bar(position = \"fill\") +\n    scale_x_continuous(breaks = 0:23) +\n    labs(\n      title = \"Proporción de accidentes con víctimas por hora\",\n      x = \"Hora del día\",\n      y = \"Proporción\",\n      fill = \"Clase\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](03-analisis-exploratorio_files/figure-html/unnamed-chunk-22-1.png){width=840}\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Relación entre día de la semana y presencia de víctimas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  ggplot(atus_ml, aes(x = DIASEMANA, fill = accidente_con_victimas)) +\n    geom_bar(position = \"fill\") +\n    coord_flip() +\n    labs(\n      title = \"Proporción de accidentes con víctimas por día de la semana\",\n      x = \"Día de la semana\",\n      y = \"Proporción\",\n      fill = \"Clase\"\n    )\n}\n```\n\n::: {.cell-output-display}\n![](03-analisis-exploratorio_files/figure-html/unnamed-chunk-23-1.png){width=840}\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Tabla resumen por clase\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!is.null(atus_ml)) {\n  resumen_clase <- atus_ml |>\n    group_by(accidente_con_victimas) |>\n    summarise(\n      total = n(),\n      hora_promedio = mean(ID_HORA_NUM, na.rm = TRUE),\n      hora_minima = min(ID_HORA_NUM, na.rm = TRUE),\n      hora_maxima = max(ID_HORA_NUM, na.rm = TRUE),\n      .groups = \"drop\"\n    )\n\n  resumen_clase\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  accidente_con_victimas  total hora_promedio hora_minima hora_maxima\n  <fct>                   <int>         <dbl>       <dbl>       <dbl>\n1 Con víctimas            68108          13.6           0          23\n2 Solo daños             322519          13.7           0          23\n```\n\n\n:::\n:::\n\n\n**Explicación del código.**  \nEste bloque realiza una operación de análisis exploratorio: carga datos, transforma variables, calcula frecuencias o construye una gráfica. La finalidad es conocer mejor la estructura de la base antes de modelar.\n\n**Interpretación del resultado.**  \nLa salida debe leerse como una evidencia descriptiva: ayuda a identificar patrones, desbalances, categorías frecuentes o relaciones preliminares entre variables. No implica causalidad, pero orienta el análisis posterior.\n\n\n## Conclusión\n\nEn este capítulo aprendimos a cargar una base preparada, revisar dimensiones, analizar la variable respuesta, construir tablas de frecuencia, graficar accidentes por mes, hora, día, tipo y causa, e interpretar patrones iniciales.\n\nEn el siguiente capítulo construiremos nuestro primer modelo supervisado para clasificación: una **regresión logística**.\n",
    "supporting": [
      "03-analisis-exploratorio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}